# This playbook automates configuring Tower for an individual workflow
# approval gate.
#
# See documentation for the `approval-base` and `approval-gate-config`
# roles for more information on requirements and parameters.
---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    - approval-base
    - approval-gate-config
