---
- name: Create a Workflow Approval Gate credential specifically for this gate
  command: >
    tower-cli credential create
    --format json
    --force-on-exists
    --name "Approval Gate / {{ approval_gate_name }}"
    --organization "Workflow Approvals"
    --credential-type "Workflow Approval Gate"
    --inputs "{{ inputs | from_yaml | to_yaml }}"
  no_log: yes
  vars:
    inputs: |
      host: https://localhost
      {{ lookup('pipe', 'tower-cli config username') }}
      {{ lookup('pipe', 'tower-cli config password') }}
      approval_gate_name: {{ approval_gate_name }}
  register: create_gate_cred
  changed_when: (create_gate_cred.stdout | from_json).changed
- name: Create a team that will handle approvals for this gate
  command: >
    tower-cli team create
    --format json
    --force-on-exists
    --name "Approval Gate / {{ approval_gate_name }}"
    --organization "Workflow Approvals"
  register: create_team
  changed_when: (create_team.stdout | from_json).changed
- name: Grant the approval gate team permission to use the approvals inventory
  command: >
    tower-cli role grant
    --format json
    --inventory "Workflow Approvals"
    --team "Approval Gate / {{ approval_gate_name }}"
    --type use
  register: grant_team_inventory_permission
  changed_when: (grant_team_inventory_permission.stdout | from_json).changed
- name: Grant the approval gate team permission to use the approvals credential
  command: >
    tower-cli role grant
    --format json
    --credential "Approval Gate / {{ approval_gate_name }}"
    --team "Approval Gate / {{ approval_gate_name }}"
    --type use
  register: grant_team_gate_cred_permission
  changed_when: (grant_team_gate_cred_permission.stdout | from_json).changed
- name: Grant the approval gate team permission to use the machine credential
  command: >
    tower-cli role grant
    --format json
    --credential "Workflow Approvals"
    --team "Approval Gate / {{ approval_gate_name }}"
    --type use
  register: grant_team_machine_cred_permission
  changed_when: (grant_team_machine_cred_permission.stdout | from_json).changed
- name: Grant the approval gate team permission to use the approvals project
  command: >
    tower-cli role grant
    --format json
    --project "Workflow Approvals"
    --team "Approval Gate / {{ approval_gate_name }}"
    --type use
  register: grant_team_project_permission
  changed_when: (grant_team_project_permission.stdout | from_json).changed
- name: Create a label for this gate
  command: >
    tower-cli label create
    --format json
    --force-on-exists
    --name "{{ approval_gate_name }} Gate"
    --organization "Workflow Approvals"
  register: create_gate_label
  changed_when: (create_gate_label.stdout | from_json).changed
